---
- name: Playbook to create a basic jekyll site
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Create Jekyll Group
      clc_group:
        location: 'UC1'
        name: 'Jekyll'
        state: present
      register: clc_grp

    - debug: var=clc_grp

    - name: Create Jekyll Server
      clc_server:
        name: jekyll
        template: ubuntu-14-64
        location: 'UC1'
        group: 'Jekyll'
        count_group: 'Jekyll'
        exact_count: 1
        password: abc123!$#
      register: clc_svr

    - debug: var=clc_svr

    - name: Create Public IP for the server
      clc_publicip:
        server_ids: "{{ clc_svr.servers.name }}"
        ports:
          - "80"
          - "443"
        state: present
        with_flattened: clc_svr.servers

    - name: Add the new server to the inventory
      add_host: name={{clc_svr.servers[0].name}}  groups=jekyll_group ansible_ssh_pass=abc123!$# ansible_connection=ssh ansible_ssh_host={{clc_svr.servers[0].ipaddress}} ansible_ssh_user=root


- hosts: jekyll_group
  tasks:
    - name: Refresh apt Cache
      apt: update_cache=yes

    - name: Install make
      apt: name=make state=present

    - name: Install nodejs
      apt: name=nodejs state=present

    - name: Install ruby
      apt: name=ruby-full state=present

    - name: Install Jekyll
      shell: gem install jekyll

    - name: Create Blog Directory
      file: path=/data01 state=directory mode=0755

    - name: Create the Site
      shell: jekyll new /data01/myBlog

    - name: Run the Jekyll Service
      shell: jekyll serve --source /data01/myBlog --destination /data01/myBlog/_site --detach --host $(hostname -I)
